### ISSUE TITLE
可以做成订阅，用switchhosts去自动更新

### ISSUE THREAD

**Issue by abcmiao** [maxiaof/github-hosts#3]
大佬，可以考虑将这个要修改的内容做成链接，然后用switchhosts去订阅你，macOS,windows都支持
<img width="802" alt="image" src="https://github.com/maxiaof/github-hosts/assets/13944985/9940799c-08e8-48aa-89bc-3dc1a2242f3b">

我自己用与更新adobe屏蔽的hosts

介绍：https://www.appmiu.com/17922.html

**Comment by flovel** [comment]
https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts

**Comment by abcmiao** [comment]
> https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts

这个链接行，初次使用不知道会不会有网络无法访问的问题

**Comment by maxiaof** [comment]
> > https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts
> 
> 这个链接不行，初次使用会有无法访问的问题，更新之后也没办法在不开代理的情况下更新
> 
> 要是能搞个国内能访问的直链就更好了，我有点想尽一份力，但是又怕墙我域名😭

使用  https://cdn.jsdelivr.net/gh/maxiaof/github-hosts/hosts

**Comment by CsVeryLoveXieWenLi** [comment]
> > https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts
> 
> 这个链接不行，初次使用会有无法访问的问题，更新之后也没办法在不开代理的情况下更新
> 
> 要是能搞个国内能访问的直链就更好了，我有点想尽一份力，但是又怕墙我域名😭

**可以选择请求各大镜像站，或者使用Github镜像，这样就无需使用自己的东西。**

**不过，这并不是长久之计，上上策仍然是自行搭建或使用魔法。**

**Comment by CsVeryLoveXieWenLi** [comment]
> > https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts
> 
> 这个链接不行，初次使用会有无法访问的问题，更新之后也没办法在不开代理的情况下更新
> 
> 要是能搞个国内能访问的直链就更好了，我有点想尽一份力，但是又怕墙我域名😭

**当然，也可托管到NPM，使用NPM镜像。不过，据我所知，有些NPM镜像也提供Github格式。**

**Comment by CsVeryLoveXieWenLi** [comment]
> > https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts
> 
> 这个链接不行，初次使用会有无法访问的问题，更新之后也没办法在不开代理的情况下更新
> 
> 要是能搞个国内能访问的直链就更好了，我有点想尽一份力，但是又怕墙我域名😭

**当然，用别人的东西，可是有风险的，不管如何微乎其微，包括NPM之类的。**

**GitHub Proxy. 主域名ghproxy.com 已喜提GFW，已启用镜像站mirror.ghproxy.com GitHub 文件, Releases , archive , gist , raw.githubusercontent.com 文件代理加速下载 ...**
